<?php

use Illuminate\Database\Seeder;

class WagonsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('wagons')->truncate();

        DB::table('wagons')->insert([
            [
                "creator_id" => 1,
                "inw" => "63746051",
                "arrived_at" => null,
                "detained_at" => "2019-08-12 16:40:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 7,
                "reason" => null,
                "cargo" => null,
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => null,
                "destination_station" => null,
                "taken_measure" => null,
                "operation" => "unloading",
                "park" => "3",
                "way" => "5",
                "nplf" => "162900",
            ],
            [
                "creator_id" => 1,
                "inw" => "63905350",
                "arrived_at" => null,
                "detained_at" => "2019-08-12 17:40:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 7,
                "reason" => null,
                "cargo" => null,
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => null,
                "destination_station" => null,
                "taken_measure" => null,
                "operation" => "unloading",
                "park" => "Г1",
                "way" => "10",
                "nplf" => "165203",
            ],
            [
                "creator_id" => 1,
                "inw" => "91570887",
                "arrived_at" => null,
                "detained_at" => "2019-08-12 13:10:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 7,
                "reason" => null,
                "cargo" => null,
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => null,
                "destination_station" => null,
                "taken_measure" => null,
                "operation" => "unloading",
                "park" => "3",
                "way" => "5",
                "nplf" => "162900",
            ],
            [
                "creator_id" => 1,
                "inw" => "92623289",
                "arrived_at" => null,
                "detained_at" => "2019-08-11 12:30:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 7,
                "reason" => null,
                "cargo" => null,
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => null,
                "destination_station" => null,
                "taken_measure" => null,
                "operation" => "unloading",
                "park" => "3",
                "way" => "5",
                "nplf" => "160002",
            ],
            [
                "creator_id" => 1,
                "inw" => "74895509",
                "arrived_at" => "2019-07-24 01:15:00",
                "detained_at" => "2019-07-24 10:16:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "неисп.м.р.сп",
                "cargo" => "Бензин",
                "forwarder" => null,
                "ownership" => "БЧ",
                "departure_station" => "Барбаров",
                "destination_station" => "Полоцк",
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "92623289",
                "arrived_at" => "2019-08-11 02:44:00",
                "detained_at" => "2019-08-11 15:48:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Трещина, излом лестницы",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Полоцк",
                "destination_station" => null,
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "62284575",
                "arrived_at" => "2019-08-11 18:09:00",
                "detained_at" => "2019-08-11 20:29:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Даугавпилс",
                "destination_station" => null,
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60506557",
                "arrived_at" => "2019-08-11 19:55:00",
                "detained_at" => "2019-08-11 20:55:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Завар башмака",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Лиепая",
                "destination_station" => null,
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "62399076",
                "arrived_at" => "2019-08-11 18:09:00",
                "detained_at" => "2019-08-11 20:20:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Даугавпилс",
                "destination_station" => null,
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "95003422",
                "arrived_at" => "2019-08-12 22:18:00",
                "detained_at" => "2019-08-12 22:32:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Щепа",
                "forwarder" => null,
                "ownership" => "БЧ",
                "departure_station" => "Парафьянов",
                "destination_station" => "Лиепая",
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "63905350",
                "arrived_at" => "2019-08-12 09:29:00",
                "detained_at" => "2019-08-13 03:01:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Обрав свар шва стойки",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Полоцк",
                "destination_station" => null,
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "94523727",
                "arrived_at" => "2019-08-11 01:06:00",
                "detained_at" => "2019-08-11 08:40:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Техбрак в связи с неприемом Лат.ж.д.. Нет одного торцевого борта",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Брест-Северный",
                "destination_station" => "Даугавпилс",
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "95009486",
                "arrived_at" => "2019-08-13 19:25:00",
                "detained_at" => "2019-08-13 20:50:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Опилки",
                "forwarder" => null,
                "ownership" => null,
                "departure_station" => "Молодечно",
                "destination_station" => "Лиепая",
                "taken_measure" => "В ожидании ремонта",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "50658228",
                "arrived_at" => "2019-08-06 21:32:00",
                "detained_at" => "2019-08-06 21:57:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Неисправность поглощающего аппарата",
                "cargo" => "Дисцилляты газового конденсата",
                "forwarder" => "ООО БелКазТранс",
                "ownership" => "ООО Русский мир",
                "departure_station" => "Полотняный заврд",
                "destination_station" => "Мангали",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №128 от 07.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "62866629",
                "arrived_at" => "2019-08-09 01:22:00",
                "detained_at" => "2019-08-09 01:41:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Обрыв заклепки фрикционной планки",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "ООО Восток",
                "departure_station" => "Разрез",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №163 от 09.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60305042",
                "arrived_at" => "2019-08-09 16:01:00",
                "detained_at" => "2019-08-09 16:26:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Нагрев подшипника",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Ерунаково",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №188 от 10.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "68172444",
                "arrived_at" => "2019-08-10 01:50:00",
                "detained_at" => "2019-08-10 02:17:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "Альфа-Лизинг",
                "departure_station" => "Разрез",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №190 от 10.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60864766",
                "arrived_at" => "2019-08-10 03:32:00",
                "detained_at" => "2019-08-10 03:36:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Мереть",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №187 от 10.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "61333886",
                "arrived_at" => "2019-08-10 04:45:00",
                "detained_at" => "2019-08-10 04:53:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Мереть",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №191 от 10.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "64467053",
                "arrived_at" => "2019-08-10 05:55:00",
                "detained_at" => "2019-08-10 06:00:00",
                "released_at" => "2019-08-10 15:40:00",
                "departed_at" => "2019-09-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Щепа",
                "forwarder" => null,
                "ownership" => "БЧ",
                "departure_station" => "Крупки",
                "destination_station" => "Мангали",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "58344284",
                "arrived_at" => "2019-08-10 11:41:00",
                "detained_at" => "2019-08-10 12:05:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Излом, ослабление расцепного привода",
                "cargo" => "Бензин",
                "forwarder" => "ЛДЗ Логистика",
                "ownership" => "ООО ГР Лизинг",
                "departure_station" => "Биклянь",
                "destination_station" => "Вентспилс",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "62712245",
                "arrived_at" => "2019-08-11 09:29:00",
                "detained_at" => "2019-08-11 09:47:00",
                "released_at" => "2019-08-12 16:30:00",
                "departed_at" => "2019-08-14 02:33:00",
                "detainer_id" => 1,
                "reason" => "Неисправность запора люка",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Терентьевская",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №204 от 12.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "73351710",
                "arrived_at" => "2019-08-12 00:40:00",
                "detained_at" => "2019-08-12 00:59:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Газойль",
                "forwarder" => "ООО Мозырьский НПЗ",
                "ownership" => null,
                "departure_station" => "Барбаров",
                "destination_station" => "Мангали",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "73051780",
                "arrived_at" => "2019-08-12 00:40:00",
                "detained_at" => "2019-08-12 00:59:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Трещина запасного резервуара",
                "cargo" => "Газойль",
                "forwarder" => "ООО Мозырьский НПЗ",
                "ownership" => null,
                "departure_station" => "Барбаров",
                "destination_station" => "Мангали",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "95408712",
                "arrived_at" => "2019-08-12 00:40:00",
                "detained_at" => "2019-08-12 00:50:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Неисправность, не связанная с тех. состоянием",
                "cargo" => "Порожний",
                "forwarder" => "ЛДЗ Логистика",
                "ownership" => null,
                "departure_station" => "Коростень-Подольский",
                "destination_station" => "Даугавпилс",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "73516981",
                "arrived_at" => "2019-08-12 00:40:00",
                "detained_at" => "2019-08-12 01:15:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Мазут",
                "forwarder" => "ООО Мозырьский НПЗ",
                "ownership" => null,
                "departure_station" => "Барбаров",
                "destination_station" => "Вентспилс",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "61394615",
                "arrived_at" => "2019-08-12 01:40:00",
                "detained_at" => "2019-08-12 01:55:00",
                "released_at" => "2019-08-16 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ВТБ-Лизинг",
                "departure_station" => "Миреть",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №227 от 13.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60255825",
                "arrived_at" => "2019-08-12 08:19:00",
                "detained_at" => "2019-08-12 08:21:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Мереть",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №224 от 13.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "58269101",
                "arrived_at" => "2019-08-13 03:52:00",
                "detained_at" => "2019-08-13 04:05:00",
                "released_at" => "2019-08-13 16:20:00",
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Неисправность поглощающего аппарата",
                "cargo" => "Газы нефтяные",
                "forwarder" => "ООО Белинтертранс",
                "ownership" => "ООО Сырьевые ресурсы",
                "departure_station" => "Витьба",
                "destination_station" => "Болдерая",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №232 от 13.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60631686",
                "arrived_at" => "2019-08-13 04:14:00",
                "detained_at" => "2019-08-13 04:34:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Обрыв сварного шва",
                "cargo" => "Уголь",
                "forwarder" => "Белинтертранс",
                "ownership" => "МТ",
                "departure_station" => "Забойщик",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма №231 от 13.08.2019 г.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "62243738",
                "arrived_at" => "2019-08-13 09:40:00",
                "detained_at" => "2019-08-13 09:47:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Неисправность запора люка",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО Сбербанк-Лизинг",
                "departure_station" => "Терентьевская",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "62711460",
                "arrived_at" => "2019-08-13 09:40:00",
                "detained_at" => "2019-08-13 09:47:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Неисправность запора люка",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Терентьевская",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60345576",
                "arrived_at" => "2019-08-13 11:48:00",
                "detained_at" => "2019-08-13 12:03:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Белинтертранс",
                "ownership" => "АО Сбербанк-Лизинг",
                "departure_station" => "Терентьевская",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "74721077",
                "arrived_at" => "2019-08-07 13:44:00",
                "detained_at" => "2019-08-07 14:18:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Техбрак в связи с неприемом Лат.ж.д. Прибыл с разоборудованным ручным стояночным тормозом",
                "cargo" => "Бензин моторный",
                "forwarder" => "ООО Мозырьский НПЗ",
                "ownership" => "Литва",
                "departure_station" => "Барбаров",
                "destination_station" => "Венспилс-эксп.",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "76620715",
                "arrived_at" => "2019-08-13 22:41:00",
                "detained_at" => "2019-08-13 22:44:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Неисправность поглощающего аппарата",
                "cargo" => "Порожний",
                "forwarder" => null,
                "ownership" => "ООО Сырьевые ресурсы",
                "departure_station" => "Витьба",
                "destination_station" => "Новополоцк",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "74811738",
                "arrived_at" => "2019-08-13 22:41:00",
                "detained_at" => "2019-08-13 23:24:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Нефтепродукты светлые",
                "forwarder" => "Белинтертранс",
                "ownership" => null,
                "departure_station" => "Шебелинка",
                "destination_station" => "Венспилс",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "73997744",
                "arrived_at" => "2019-08-14 01:44:00",
                "detained_at" => "2019-08-14 02:03:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Газойль",
                "forwarder" => "ООО Мозырьский НПЗ",
                "ownership" => null,
                "departure_station" => "Барбаров",
                "destination_station" => "Мангали",
                "taken_measure" => "В ожидании ремонта.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "55794614",
                "arrived_at" => "2019-08-14 06:22:00",
                "detained_at" => "2019-08-14 06:32:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Обрыв / трещина маятниковой подвески",
                "cargo" => "Уголь",
                "forwarder" => null,
                "ownership" => "АО ВЭБ-Лизинг",
                "departure_station" => "Забойщик",
                "destination_station" => "Криеву Сала",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "60151016",
                "arrived_at" => "2019-08-14 06:58:00",
                "detained_at" => "2019-08-14 07:04:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Уголь",
                "forwarder" => "Авантрейл",
                "ownership" => "АО ФГК",
                "departure_station" => "Ерунаково",
                "destination_station" => "Вентспилс",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ],
            [
                "creator_id" => 1,
                "inw" => "61349189",
                "arrived_at" => "2019-09-14 06:58:00",
                "detained_at" => "2019-08-14 07:03:00",
                "released_at" => null,
                "departed_at" => null,
                "detainer_id" => 1,
                "reason" => "Излом пружин",
                "cargo" => "Антрацит",
                "forwarder" => "Стар Роуд ЛТД",
                "ownership" => "АО ФГК",
                "departure_station" => "Рыбное",
                "destination_station" => "Вентспилс",
                "taken_measure" => "В ожидании ремонта. Дана телеграмма.",
                "operation" => "loading",
                "park" => null,
                "way" => null,
                "nplf" => null,
            ]
        ]);
    }
}
